In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('FakeScore.csv')

df = df.rename(columns={'Unnamed: 0': 'Name'})

display(df)

     Name  Math  English  Science
0       0    42       76       78
1       1     8       71       14
2       2    79       19       31
3       3    87       96       15
4       4    80       10       12
..    ...   ...      ...      ...
995   995    81       84       20
996   996    71       93       38
997   997    91       83       70
998   998    84       90       16
999   999    20       33       92

[1000 rows x 4 columns]

In [6]:
#function
def categorize_score(score):

    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:
        return "E"

In [7]:
math = df['Math'].tolist()
result_for_math = []
for i in math:
    grade = categorize_score(i)
    #print(grade)
    result_for_math += grade
print(result_for_math)

english = df['English'].tolist()
result_for_english = []
for i in english:
    grade = categorize_score(i)
    #print(grade)
    result_for_english += grade
print(result_for_english)


sci = df['Science'].tolist()
result_for_sci = []
for i in sci:
    grade = categorize_score(i)
    #print(grade)
    result_for_sci += grade
print(result_for_sci)

['E', 'E', 'C', 'B', 'B', 'E', 'C', 'B', 'B', 'B', 'E', 'E', 'E', 'E', 'B', 'D', 'E', 'E', 'C', 'E', 'A', 'E', 'E', 'D', 'E', 'D', 'E', 'E', 'D', 'E', 'E', 'D', 'C', 'C', 'D', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'C', 'C', 'E', 'E', 'E', 'D', 'A', 'E', 'D', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'B', 'E', 'E', 'E', 'E', 'D', 'E', 'C', 'B', 'D', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'A', 'D', 'A', 'E', 'B', 'E', 'C', 'B', 'A', 'E', 'C', 'D', 'A', 'E', 'B', 'B', 'E', 'C', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'D', 'A', 'E', 'A', 'C', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'A', 'C', 'E', 'C', 'E', 'E', 'A', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'D', 'B', 'E', 'D', 'E', 'A', 'C', 'C', 'D', 'E', 'C', 'D', 'E', 'A', 'E', 'A', 'A', 'E', 'D', 'E', 'E', 'D', 'E', 'E', 'B', 'E', 'E', 'A', 'D', 'C', 'E', 'E', 'D', 'E', 'E', 'D', 'C', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'A', 'C', 'E', 'C', 'C', 'E', 'D', 'E', 'D', 'E', 'E', 'C', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'A', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'D', 'E', 'E', 'D', 'E', 'E', 'C', 'A', 'E', 'B', 'B', 'E', 'E', 'E', 'C', 'E', 'E', 'C', 'E', 'E', 'C', 'C', 'D', 'B', 'E', 'E', 'E', 'C', 'C', 'E', 'B', 'C', 'E', 'E', 'B', 'B', 'C', 'E', 'E', 'E', 'D', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'B', 'E', 'B', 'B', 'E', 'B', 'B', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'C', 'A', 'D', 'E', 'D', 'B', 'C', 'C', 'E', 'E', 'E', 'E', 'B', 'A', 'C', 'C', 'E', 'E', 'D', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'D', 'D', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'D', 'A', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'D', 'C', 'B', 'E', 'E', 'E', 'A', 'E', 'E', 'A', 'E', 'D', 'C', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'C', 'E', 'B', 'E', 'B', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'C', 'E', 'B', 'E', 'E', 'C', 'D', 'E', 'B', 'A', 'E', 'E', 'E', 'A', 'B', 'E', 'C', 'E', 'E', 'A', 'B', 'D', 'E', 'A', 'C', 'A', 'D', 'B', 'E', 'E', 'B', 'D', 'C', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'A', 'E', 'B', 'C', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'A', 'C', 'E', 'E', 'C', 'D', 'E', 'E', 'A', 'B', 'E', 'C', 'C', 'E', 'E', 'E', 'A', 'C', 'E', 'E', 'E', 'A', 'E', 'D', 'E', 'C', 'E', 'D', 'D', 'D', 'B', 'B', 'E', 'E', 'E', 'E', 'D', 'E', 'A', 'E', 'E', 'A', 'E', 'A', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'A', 'A', 'E', 'D', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'D', 'B', 'E', 'B', 'D', 'E', 'E', 'E', 'A', 'D', 'E', 'A', 'E', 'E', 'D', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'C', 'E', 'D', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'B', 'E', 'A', 'E', 'D', 'E', 'E', 'E', 'D', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'C', 'B', 'C', 'A', 'E', 'B', 'E', 'E', 'A', 'B', 'E', 'E', 'A', 'E', 'D', 'B', 'E', 'E', 'E', 'B', 'A', 'B', 'B', 'E', 'E', 'E', 'E', 'A', 'C', 'C', 'D', 'E', 'E', 'E', 'B', 'E', 'D', 'A', 'D', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'C', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'B', 'E', 'E', 'C', 'E', 'E', 'C', 'D', 'E', 'E', 'E', 'E', 'A', 'A', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'B', 'E', 'E', 'A', 'D', 'D', 'D', 'E', 'E', 'E', 'E', 'C', 'E', 'A', 'C', 'A', 'A', 'A', 'A', 'E', 'A', 'D', 'E', 'A', 'A', 'D', 'A', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'C', 'D', 'C', 'E', 'A', 'D', 'E', 'A', 'A', 'C', 'E', 'D', 'E', 'A', 'B', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'A', 'E', 'E', 'A', 'B', 'A', 'D', 'E', 'A', 'E', 'E', 'D', 'B', 'E', 'E', 'C', 'E', 'A', 'E', 'E', 'C', 'E', 'E', 'E', 'B', 'A', 'E', 'A', 'E', 'E', 'E', 'E', 'B', 'A', 'C', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'D', 'E', 'A', 'E', 'D', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'B', 'A', 'A', 'E', 'E', 'A', 'E', 'E', 'D', 'E', 'E', 'D', 'E', 'E', 'B', 'A', 'E', 'C', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'C', 'E', 'E', 'D', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'B', 'E', 'E', 'B', 'E', 'C', 'E', 'E', 'D', 'D', 'E', 'E', 'C', 'E', 'E', 'D', 'E', 'E', 'A', 'A', 'A', 'B', 'E', 'E', 'B', 'A', 'E', 'C', 'E', 'E', 'D', 'E', 'E', 'A', 'A', 'A', 'B', 'E', 'A', 'E', 'E', 'D', 'E', 'E', 'E', 'D', 'E', 'C', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'C', 'E', 'A', 'A', 'D', 'E', 'E', 'B', 'E', 'B', 'E', 'E', 'D', 'E', 'B', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'C', 'E', 'E', 'B', 'C', 'C', 'E', 'E', 'D', 'A', 'B', 'A', 'E', 'E', 'D', 'C', 'E', 'E', 'A', 'E', 'B', 'E', 'E', 'B', 'A', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'C', 'C', 'E', 'E', 'B', 'E', 'C', 'C', 'A', 'C', 'E', 'E', 'E', 'C', 'C', 'D', 'B', 'C', 'E', 'E', 'A', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'A', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'A', 'D', 'E', 'E', 'C', 'E', 'D', 'B', 'C', 'A', 'B', 'E']
['C', 'C', 'E', 'A', 'E', 'B', 'E', 'C', 'E', 'E', 'A', 'E', 'E', 'D', 'C', 'E', 'A', 'A', 'E', 'A', 'C', 'C', 'B', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'C', 'E', 'D', 'E', 'A', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'D', 'D', 'E', 'D', 'C', 'E', 'B', 'E', 'E', 'D', 'A', 'E', 'D', 'E', 'A', 'A', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'C', 'A', 'E', 'E', 'D', 'D', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'B', 'A', 'E', 'B', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'C', 'A', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'D', 'B', 'E', 'E', 'E', 'C', 'B', 'E', 'E', 'C', 'C', 'B', 'B', 'B', 'D', 'E', 'C', 'E', 'B', 'D', 'E', 'E', 'E', 'E', 'D', 'A', 'A', 'D', 'D', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'C', 'E', 'E', 'A', 'C', 'B', 'E', 'E', 'D', 'B', 'A', 'D', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'D', 'B', 'B', 'D', 'C', 'B', 'B', 'E', 'E', 'A', 'C', 'E', 'B', 'D', 'B', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'B', 'D', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'A', 'E', 'E', 'E', 'B', 'C', 'A', 'C', 'E', 'B', 'E', 'E', 'E', 'E', 'C', 'B', 'E', 'C', 'E', 'E', 'E', 'A', 'E', 'B', 'C', 'E', 'E', 'C', 'E', 'C', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'E', 'E', 'C', 'B', 'E', 'D', 'A', 'E', 'C', 'D', 'C', 'A', 'E', 'E', 'C', 'E', 'B', 'A', 'C', 'E', 'E', 'E', 'A', 'B', 'A', 'E', 'B', 'C', 'E', 'E', 'B', 'E', 'B', 'C', 'E', 'E', 'E', 'E', 'C', 'E', 'A', 'E', 'E', 'D', 'E', 'E', 'D', 'B', 'C', 'D', 'E', 'B', 'E', 'C', 'E', 'E', 'A', 'E', 'E', 'C', 'E', 'A', 'E', 'E', 'E', 'A', 'E', 'B', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'B', 'C', 'E', 'D', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'A', 'E', 'D', 'E', 'B', 'E', 'C', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'B', 'B', 'B', 'B', 'E', 'E', 'C', 'D', 'E', 'B', 'E', 'D', 'E', 'B', 'E', 'E', 'E', 'B', 'E', 'A', 'C', 'E', 'A', 'C', 'E', 'E', 'A', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'D', 'D', 'E', 'E', 'E', 'E', 'D', 'A', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'D', 'B', 'E', 'E', 'E', 'D', 'E', 'E', 'C', 'D', 'E', 'D', 'E', 'E', 'C', 'E', 'E', 'E', 'C', 'B', 'B', 'E', 'C', 'E', 'A', 'A', 'E', 'C', 'C', 'C', 'A', 'D', 'C', 'B', 'E', 'E', 'E', 'E', 'C', 'C', 'D', 'E', 'D', 'B', 'A', 'A', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'D', 'A', 'D', 'C', 'A', 'E', 'B', 'E', 'E', 'A', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'A', 'C', 'D', 'E', 'E', 'E', 'A', 'C', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'A', 'D', 'B', 'B', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'C', 'E', 'A', 'E', 'E', 'D', 'E', 'B', 'E', 'D', 'D', 'E', 'A', 'E', 'E', 'E', 'B', 'A', 'A', 'E', 'A', 'B', 'D', 'D', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'B', 'E', 'B', 'E', 'E', 'E', 'A', 'A', 'B', 'C', 'C', 'E', 'E', 'E', 'D', 'C', 'E', 'E', 'B', 'E', 'E', 'B', 'E', 'E', 'E', 'D', 'E', 'C', 'C', 'A', 'E', 'B', 'B', 'E', 'A', 'E', 'C', 'C', 'E', 'E', 'D', 'E', 'B', 'E', 'A', 'A', 'E', 'C', 'E', 'C', 'E', 'E', 'E', 'E', 'C', 'D', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'A', 'A', 'A', 'B', 'E', 'E', 'E', 'C', 'B', 'E', 'A', 'A', 'E', 'E', 'E', 'A', 'E', 'E', 'B', 'E', 'E', 'A', 'D', 'D', 'E', 'E', 'C', 'E', 'E', 'D', 'D', 'E', 'B', 'E', 'C', 'E', 'B', 'A', 'E', 'E', 'B', 'D', 'E', 'D', 'E', 'C', 'E', 'B', 'D', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'B', 'B', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'D', 'E', 'C', 'A', 'B', 'E', 'C', 'C', 'C', 'A', 'E', 'E', 'E', 'C', 'E', 'E', 'A', 'B', 'A', 'A', 'E', 'E', 'C', 'C', 'A', 'E', 'E', 'E', 'A', 'E', 'E', 'D', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'C', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'C', 'E', 'D', 'E', 'E', 'C', 'E', 'B', 'E', 'E', 'E', 'E', 'C', 'E', 'D', 'E', 'E', 'D', 'E', 'E', 'B', 'E', 'C', 'D', 'A', 'E', 'E', 'D', 'E', 'E', 'D', 'E', 'D', 'E', 'B', 'C', 'E', 'E', 'B', 'B', 'E', 'A', 'E', 'C', 'C', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'D', 'E', 'E', 'A', 'A', 'C', 'E', 'D', 'C', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'A', 'D', 'E', 'D', 'C', 'E', 'E', 'C', 'A', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'A', 'A', 'D', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'D', 'E', 'E', 'E', 'A', 'A', 'E', 'E', 'E', 'B', 'D', 'D', 'C', 'B', 'D', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'C', 'E', 'C', 'E', 'C', 'E', 'C', 'E', 'E', 'E', 'D', 'A', 'E', 'E', 'E', 'E', 'E', 'C', 'C', 'E', 'D', 'D', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'D', 'A', 'A', 'E', 'E', 'E', 'B', 'E', 'D', 'E', 'E', 'E', 'C', 'B', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'D', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'D', 'E', 'E', 'A', 'E', 'B', 'A', 'B', 'A', 'E']
['C', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'A', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'C', 'E', 'B', 'B', 'A', 'E', 'E', 'B', 'A', 'D', 'C', 'E', 'E', 'C', 'A', 'E', 'E', 'E', 'E', 'B', 'E', 'A', 'E', 'A', 'B', 'D', 'E', 'E', 'E', 'A', 'E', 'B', 'D', 'A', 'E', 'D', 'B', 'C', 'E', 'D', 'B', 'E', 'E', 'A', 'E', 'D', 'E', 'A', 'B', 'B', 'E', 'E', 'E', 'E', 'B', 'A', 'E', 'E', 'B', 'A', 'C', 'E', 'E', 'C', 'A', 'E', 'A', 'C', 'E', 'E', 'B', 'E', 'E', 'D', 'E', 'D', 'E', 'D', 'E', 'E', 'E', 'D', 'D', 'E', 'E', 'A', 'E', 'E', 'D', 'E', 'C', 'E', 'B', 'C', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'C', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'B', 'D', 'B', 'E', 'A', 'B', 'A', 'D', 'E', 'A', 'B', 'E', 'A', 'B', 'E', 'B', 'E', 'E', 'E', 'D', 'E', 'D', 'E', 'A', 'C', 'D', 'E', 'E', 'E', 'E', 'B', 'D', 'E', 'D', 'B', 'E', 'E', 'E', 'E', 'C', 'D', 'C', 'C', 'E', 'B', 'E', 'E', 'E', 'D', 'D', 'B', 'E', 'E', 'E', 'E', 'C', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'E', 'B', 'A', 'E', 'E', 'E', 'E', 'A', 'D', 'E', 'E', 'E', 'C', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'A', 'E', 'E', 'D', 'C', 'C', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'D', 'E', 'E', 'B', 'D', 'E', 'D', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'D', 'E', 'C', 'E', 'A', 'B', 'D', 'E', 'B', 'C', 'D', 'E', 'E', 'D', 'D', 'E', 'A', 'D', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'A', 'D', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'D', 'D', 'E', 'C', 'E', 'A', 'B', 'E', 'E', 'E', 'E', 'B', 'E', 'C', 'E', 'D', 'B', 'E', 'C', 'E', 'E', 'E', 'C', 'C', 'C', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'A', 'D', 'E', 'A', 'E', 'D', 'A', 'E', 'E', 'E', 'E', 'D', 'C', 'A', 'E', 'C', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'C', 'E', 'E', 'B', 'E', 'E', 'E', 'D', 'E', 'D', 'E', 'E', 'E', 'D', 'E', 'A', 'B', 'E', 'E', 'E', 'A', 'A', 'A', 'E', 'E', 'E', 'E', 'D', 'E', 'A', 'E', 'B', 'B', 'D', 'E', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'A', 'B', 'E', 'D', 'D', 'E', 'E', 'D', 'C', 'C', 'E', 'B', 'D', 'B', 'E', 'A', 'E', 'A', 'E', 'B', 'D', 'E', 'E', 'A', 'E', 'E', 'A', 'E', 'B', 'D', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'D', 'A', 'A', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'B', 'E', 'B', 'D', 'E', 'C', 'E', 'E', 'A', 'E', 'D', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'B', 'E', 'E', 'D', 'A', 'A', 'C', 'E', 'E', 'E', 'E', 'E', 'D', 'B', 'E', 'E', 'E', 'B', 'D', 'E', 'A', 'E', 'E', 'B', 'E', 'C', 'A', 'B', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'E', 'D', 'C', 'B', 'D', 'E', 'E', 'A', 'E', 'A', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'A', 'C', 'B', 'E', 'D', 'E', 'E', 'E', 'D', 'E', 'D', 'E', 'A', 'E', 'D', 'E', 'C', 'E', 'C', 'C', 'C', 'E', 'C', 'E', 'E', 'E', 'B', 'E', 'B', 'E', 'E', 'E', 'D', 'D', 'C', 'D', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'B', 'E', 'A', 'E', 'B', 'E', 'E', 'E', 'E', 'D', 'A', 'E', 'A', 'E', 'E', 'E', 'E', 'C', 'D', 'E', 'E', 'E', 'A', 'E', 'C', 'E', 'A', 'E', 'B', 'E', 'E', 'D', 'E', 'B', 'C', 'E', 'C', 'E', 'C', 'E', 'E', 'A', 'C', 'C', 'A', 'D', 'A', 'E', 'E', 'E', 'B', 'B', 'E', 'E', 'E', 'E', 'A', 'E', 'E', 'B', 'D', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'C', 'D', 'C', 'E', 'E', 'C', 'E', 'A', 'A', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'C', 'E', 'E', 'C', 'E', 'E', 'D', 'D', 'A', 'E', 'E', 'A', 'C', 'B', 'B', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'B', 'E', 'E', 'C', 'E', 'E', 'B', 'E', 'A', 'E', 'E', 'C', 'E', 'E', 'E', 'A', 'B', 'E', 'C', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'D', 'B', 'D', 'E', 'E', 'C', 'B', 'A', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'A', 'B', 'E', 'E', 'E', 'A', 'D', 'C', 'D', 'B', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'A', 'C', 'E', 'B', 'A', 'B', 'D', 'E', 'E', 'E', 'B', 'C', 'E', 'C', 'A', 'B', 'B', 'E', 'D', 'D', 'E', 'E', 'E', 'C', 'B', 'E', 'C', 'A', 'E', 'E', 'C', 'A', 'E', 'E', 'D', 'E', 'E', 'B', 'C', 'A', 'E', 'E', 'C', 'C', 'D', 'E', 'E', 'B', 'E', 'D', 'E', 'E', 'E', 'C', 'E', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'B', 'B', 'A', 'E', 'E', 'A', 'E', 'C', 'D', 'C', 'A', 'A', 'E', 'C', 'E', 'E', 'E', 'B', 'E', 'C', 'E', 'E', 'C', 'C', 'D', 'E', 'A', 'B', 'E', 'A', 'D', 'C', 'E', 'E', 'E', 'D', 'E', 'E', 'E', 'E', 'B', 'E', 'A', 'E', 'B', 'D', 'A', 'E', 'E', 'A', 'A', 'A', 'C', 'D', 'B', 'E', 'E', 'E', 'E', 'E', 'A', 'A', 'A', 'E', 'E', 'B', 'E', 'E', 'E', 'E', 'C', 'C', 'B', 'E', 'C', 'E', 'D', 'E', 'B', 'E', 'E', 'B', 'D', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'B', 'E', 'B', 'E', 'B', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'B', 'C', 'D', 'D', 'E', 'A', 'E', 'D', 'E', 'E', 'D', 'E', 'C', 'E', 'E', 'C', 'E', 'C', 'E', 'E', 'C', 'E', 'E', 'E', 'B', 'B', 'B', 'E', 'E', 'E', 'A', 'E', 'E', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'E', 'B', 'E', 'E', 'E', 'B', 'A', 'E', 'E', 'E', 'E', 'E', 'E', 'C', 'E', 'A']

In [8]:
df['Math_cat'] = result_for_math

df['English_cat'] = result_for_english

df['Sci_cat'] = result_for_sci
df

     Name  Math  English  Science Math_cat English_cat Sci_cat
0       0    42       76       78        E           C       C
1       1     8       71       14        E           C       E
2       2    79       19       31        C           E       E
3       3    87       96       15        B           A       E
4       4    80       10       12        B           E       E
..    ...   ...      ...      ...      ...         ...     ...
995   995    81       84       20        B           B       E
996   996    71       93       38        C           A       E
997   997    91       83       70        A           B       C
998   998    84       90       16        B           A       E
999   999    20       33       92        E           E       A

[1000 rows x 7 columns]

In [9]:
df.drop(['Name','Math','English','Science'], axis=1)

    Math_cat English_cat Sci_cat
0          E           C       C
1          E           C       E
2          C           E       E
3          B           A       E
4          B           E       E
..       ...         ...     ...
995        B           B       E
996        C           A       E
997        A           B       C
998        B           A       E
999        E           E       A

[1000 rows x 3 columns]

In [10]:
df.to_csv('FakeScoreCat.csv')